[package]
name = "nyanitor"
version = "0.1.0"
authors = ["Jade <jade@bytes.moe>"]
edition = "2018"

[dependencies]
chrono = "0.4.5"
diesel = { version = "1.0.0", features = ["postgres", "chrono"] }
dotenv = "0.9.0"
